"""ExportService — render a report dict into several formats.

md / json / html / csv are always available (pure stdlib). pdf / docx are
best-effort and require optional dependencies; the service reports which
formats are actually usable so callers can degrade gracefully.
"""
from __future__ import annotations

import csv
import io
import json
from html import escape


class ExportService:
    ALWAYS = ("markdown", "obsidian", "json", "html", "csv", "txt")

    # Human labels for the export menu (id -> button label).
    LABELS = {
        "pdf": "📄 PDF", "docx": "📝 DOCX", "markdown": "⬇️ Markdown",
        "obsidian": "🔮 Obsidian", "html": "🌐 HTML", "csv": "🔢 CSV",
        "json": "{ } JSON", "txt": "📃 TXT",
    }

    def available_formats(self) -> list[str]:
        formats = list(self.ALWAYS)
        try:
            import reportlab  # noqa: F401
            formats.insert(0, "pdf")
        except ImportError:
            pass
        try:
            import docx  # noqa: F401
            formats.insert(1, "docx")
        except ImportError:
            pass
        return formats

    def render(self, report: dict, fmt: str) -> bytes:
        fmt = fmt.lower()
        renderer = {
            "json": self._json,
            "markdown": self._markdown,
            "md": self._markdown,
            "obsidian": self._obsidian,
            "html": self._html,
            "csv": self._csv,
            "txt": self._txt,
            "pdf": self._pdf,
            "docx": self._docx,
        }.get(fmt)
        if renderer is None:
            raise ValueError(f"Unsupported export format: {fmt}")
        return renderer(report)

    def extension(self, fmt: str) -> str:
        return {"markdown": "md", "obsidian": "md"}.get(fmt.lower(), fmt.lower())

    # -- renderers ----------------------------------------------------------
    def _json(self, report: dict) -> bytes:
        return json.dumps(report, indent=2, ensure_ascii=False).encode()

    def _markdown(self, report: dict) -> bytes:
        lines = [f"# {report.get('title', 'DeathBot Report')}", ""]
        for section, body in report.get("sections", {}).items():
            lines.append(f"## {section}")
            lines.append("```")
            lines.append(body if isinstance(body, str) else json.dumps(body, indent=2))
            lines.append("```")
            lines.append("")
        return "\n".join(lines).encode()

    def _obsidian(self, report: dict) -> bytes:
        """Obsidian-flavoured markdown: YAML frontmatter + tags + callouts."""
        tags = report.get("tags") or ["deathbot"]
        created = report.get("generated_at", "")
        title = report.get("title", "DeathBot Report")
        lines = [
            "---",
            f"title: {title}",
            f"created: {created}",
            "tags:",
            *[f"  - {t}" for t in tags],
            "---",
            "",
            f"# {title}",
            "",
            f"> [!info] Generated by DeathBot{f' · {created}' if created else ''}",
            "",
        ]
        for section, body in report.get("sections", {}).items():
            text = body if isinstance(body, str) else json.dumps(body, indent=2)
            lines.append(f"## {section}")
            lines.append("")
            lines.append("```")
            lines.append(text)
            lines.append("```")
            lines.append("")
        return "\n".join(lines).encode()

    def _txt(self, report: dict) -> bytes:
        lines = [str(report.get("title", "DeathBot Report")), "=" * 40, ""]
        for section, body in report.get("sections", {}).items():
            text = body if isinstance(body, str) else json.dumps(body, indent=2)
            lines.append(f"[{section}]")
            lines.append(text)
            lines.append("")
        return "\n".join(lines).encode()

    def _html(self, report: dict) -> bytes:
        parts = [f"<h1>{escape(str(report.get('title', 'DeathBot Report')))}</h1>"]
        for section, body in report.get("sections", {}).items():
            text = body if isinstance(body, str) else json.dumps(body, indent=2)
            parts.append(f"<h2>{escape(str(section))}</h2><pre>{escape(text)}</pre>")
        return ("<!doctype html><meta charset='utf-8'>" + "".join(parts)).encode()

    def _csv(self, report: dict) -> bytes:
        buf = io.StringIO()
        writer = csv.writer(buf)
        writer.writerow(["section", "content"])
        for section, body in report.get("sections", {}).items():
            writer.writerow([section, body if isinstance(body, str) else json.dumps(body)])
        return buf.getvalue().encode()

    def _pdf(self, report: dict) -> bytes:
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.platypus import Paragraph, Preformatted, SimpleDocTemplate, Spacer
        except ImportError as exc:  # pragma: no cover
            raise ValueError("PDF export needs `reportlab` (pip install reportlab)") from exc

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, title=report.get("title", "DeathBot Report"))
        styles = getSampleStyleSheet()
        flow = [Paragraph(str(report.get("title", "DeathBot Report")), styles["Title"]),
                Spacer(1, 12)]
        for section, body in report.get("sections", {}).items():
            text = body if isinstance(body, str) else json.dumps(body, indent=2)
            flow.append(Paragraph(str(section), styles["Heading2"]))
            flow.append(Preformatted(text, styles["Code"]))
            flow.append(Spacer(1, 10))
        doc.build(flow)
        return buf.getvalue()

    def _docx(self, report: dict) -> bytes:
        try:
            from docx import Document
        except ImportError as exc:  # pragma: no cover
            raise ValueError("DOCX export needs `python-docx` (pip install python-docx)") from exc

        document = Document()
        document.add_heading(str(report.get("title", "DeathBot Report")), level=0)
        for section, body in report.get("sections", {}).items():
            text = body if isinstance(body, str) else json.dumps(body, indent=2)
            document.add_heading(str(section), level=2)
            document.add_paragraph(text)
        buf = io.BytesIO()
        document.save(buf)
        return buf.getvalue()
